### ISSUE TITLE
[Feature Request] Add setting to enable/disable automatic loading of details panel

### ISSUE THREAD

**Issue by jzetterman** [pop-os/cosmic-files#533] opened 2024-09-29 13:45 UTC
**Issue/Bug description:**
Recently Cosmic Files began automatically opening the details pane when selecting a file or folder. It would be really nice to have an option in settings to enable/disable this behavior. I don't find the details pane to be particularly useful and it loading in and out constantly to be a bad user experience. 

**Steps to reproduce:**
Open Cosmic Files, select a folder or a file, details pane loads after a short delay.

**Expected behavior:**
With the automatic loading of the details pane disabled I would be able to click on a folder or file in Cosmic Files and not have the details pane load at all.

**Comment by l-const** [comment] 2024-09-29 23:51
To add more to that, it is actually bad user experience  / disturbing when in grid view and the number of columns/rows of the grid change and as a result the selected item under the cursor is moved due to the loading of the details panel.

**Comment by iamkartiknayak** [comment] 2024-09-30 06:48
Duplicate of #483

**Comment by WatchMkr** [comment] 2024-10-02 23:30
Complete here https://github.com/pop-os/cosmic-files/issues/540

**Closed by WatchMkr** 2024-10-02 23:30 UTC
