### ISSUE TITLE
[Feature Request] Size of left frame

### ISSUE THREAD

**Issue by gantryyork** [pop-os/cosmic-files#133] opened 2024-04-27 00:33 UTC
As a user, I'd like to be able to resize the width of the left frame

**Comment by leviport** [comment] 2024-04-29 13:32
Is this not a duplicate of https://github.com/pop-os/cosmic-files/issues/70?

**Comment by leviport** [comment] 2024-05-02 17:52
Closing as a duplicate of #70

**Closed by leviport** 2024-05-02 17:52 UTC
