### ISSUE TITLE
Application does not remember it's previously selected (list)view

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-files#175] opened 2024-05-22 16:55 UTC
I'm quite used to the list view when navigating files & directories.
It would be great if Cosmic Files can remember our preference.

**Comment by WatchMkr** [comment] 2024-05-25 18:34
Duplicate of issue being tracked here: https://github.com/pop-os/cosmic-files/issues/171

**Closed by WatchMkr** 2024-05-25 18:34 UTC
