### ISSUE TITLE
[Bug] Context menu doesn't close after switching directory

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-files#529] opened 2024-09-29 05:50 UTC
**Cosmic-files version:**
0.1.0~1727571724~22.04~ad03ea7

**Issue/Bug description:**

The context menu remains open when switching directories, leaving this ugly empty space with no function.

![image](https://github.com/user-attachments/assets/7b53891f-3e22-44a6-abfd-e937510c406b)

**Steps to reproduce:**
1. Click on a file, a context menu opens.
2. Switch the current open directory through any means.
3. An empty context menu remains. 

**Expected behavior:**

It should close.

**Other notes:**
N/a

**Comment by iamkartiknayak** [comment] 2024-09-29 11:38
It looks like duplicate of #362

**Closed** 2024-09-29 11:55 UTC
