### ISSUE TITLE
Multi row naming

### ISSUE THREAD

**Issue by Lonnroth** [pop-os/cosmic-files#255] opened 2024-06-19 07:39 UTC
![image](https://github.com/pop-os/cosmic-files/assets/122230348/87cbce33-91d5-4542-ab97-45faad086aed)
As image above shows, when a name is longer than normal, it splits into two rows.
This is correct, but seeing as the letter "y" is way to the left, it looks goofy.

![image](https://github.com/pop-os/cosmic-files/assets/122230348/948b19d0-3a05-4cc7-8b24-568c2f2b7a92)
Looking at this image, you can see that just below both excel files, there are extra text, however it's not visible.

**Comment by jackpot51** [comment] 2024-07-09 17:23
Duplicate of #7.

**Closed by jackpot51** 2024-07-09 17:23 UTC
