### ISSUE TITLE
[Enchanment] cosmic-files should be able to open encrypted drive

### ISSUE THREAD

**Issue by py-crash** [pop-os/cosmic-files#383] opened 2024-08-15 07:47 UTC
cosmic-files is able to show when encrypted drives are present in the system:

![screenshot-2024-08-15-06-41-26](https://github.com/user-attachments/assets/1caa34b4-12f9-47b7-94f0-504ee144beb3)

However clicking on the drive does nothing. Expected behavior should be to open a pop up for entering the password for unlocking/mounting the drive. 

In the alpha the only workaround (using the gui) is to unlock and mount the drive using gnome-disks

**Comment by leviport** [comment] 2024-08-15 13:46
Duplicate of https://github.com/pop-os/cosmic-files/issues/144

**Closed by leviport** 2024-08-15 13:46 UTC

**Comment by py-crash** [comment] 2024-08-16 08:11
Sorry for the duplicate!

**Comment by leviport** [comment] 2024-08-16 13:52
No worries!
