### ISSUE TITLE
[BUG] Sound output devices disappear from drop-down list

### ISSUE THREAD

**Issue by LavaHeron** [pop-os/cosmic-files#636] opened 2024-11-03 20:23 UTC
**Cosmic-files version:**
0.1.0~1730233777~22.04~20f9292 (Pop!_OS 24.04 LTS - COSMIC Alpha 3)

**Issue/Bug description:**
If you set the `Output device` to `off/none`, all options disappear from the drop-down menu.

**Steps to reproduce:**
Go to `Settings` > `Sound`
Select `off/none` in the `Output device` drop-down menu.
All output devices have disappeared from the drop-down, the drop-down is empty and the sound cannot be turned back on.

**Expected behavior:**
Keep the output devices in the output device drop-down.

**Other notes:**

**Comment by l-const** [comment] 2024-11-03 20:36
Duplicate of : https://github.com/pop-os/cosmic-applets/issues/706
Certainly not a files issue.

**Closed** 2024-11-03 21:34 UTC
